name: payu_api
description: Flutter package with Payu networking mechanism.

version: 1.0.0
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  payu_core:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core

dev_dependencies:
  build_runner: ^2.2.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - ssl/entrust.pem
